### ISSUE TITLE
Wiki datasheet link is broken

### ISSUE THREAD

**Issue by JiapengLi** [Seeed-Studio/Grove_Dust_Sensor#2]
Datasheet link (http://www.seeedstudio.com/wiki/images/4/4c/Grove_-_Dust_sensor.pdf) from the wiki page (http://wiki.seeedstudio.com/wiki/Grove_-_Dust_Sensor) is dead.

Please help fix it.

**Comment by baorepo** [comment]
https://files.seeedstudio.com/wiki/Grove_Dust_Sensor/resource/Grove_-_Dust_sensor.pdf here
